/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pr_system1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class AddPatientUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddPatientUI.class.getName());

    /**
     * Creates new form AddPatientUI
     */
    public AddPatientUI() {
    initComponents();
    loadMidwivesToComboBox();
    
cbBloodType.removeAllItems(); // Clear existing default itemsa
cbBloodType.addItem("A+");
cbBloodType.addItem("A-");
cbBloodType.addItem("B+");
cbBloodType.addItem("B-");
cbBloodType.addItem("AB+");
cbBloodType.addItem("AB-");
cbBloodType.addItem("O+");
cbBloodType.addItem("O-");


    // 🧩 Restrict date inputs to numbers and slashes only
    addDateInputRestriction(txtBirthDate);
    addDateInputRestriction(txtLMP);
    addDateInputRestriction(txtEDD);

    // 🧩 Restrict numeric fields (no letters allowed)
    addNumberOnlyRestriction(txtAge);
    addNumberOnlyRestriction(txtContactNo);
    addNumberOnlyRestriction(txtGravida);
    addNumberOnlyRestriction(txtPara);   

    }
    
    private void loadMidwivesToComboBox() {
    cmbMidwives.removeAllItems(); // clear existing
    cmbMidwives.addItem("Select Midwife"); // default option

    String sql = "SELECT midwife_id, full_name FROM midwife_information ORDER BY full_name";

    try (Connection conn = DBConnection.getConnection();
         PreparedStatement pst = conn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

        while (rs.next()) {
            int id = rs.getInt("midwife_id");
            String name = rs.getString("full_name");
            cmbMidwives.addItem(id + " - " + name); // combine ID + Name
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading midwives: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtBirthDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbBloodType = new javax.swing.JComboBox<>();
        txtContactNo = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLMP = new javax.swing.JTextField();
        txtPara = new javax.swing.JTextField();
        txtGravida = new javax.swing.JTextField();
        txtEDD = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnAddPatient = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbMidwives = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 203, 456, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 195, 129, 38));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 247, 456, -1));

        txtBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 326, 456, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Last Name: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 239, 129, 38));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Birth Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 318, 129, 38));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 283, 129, 29));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 362, 129, 38));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact No.:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 406, 129, 38));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Blood Type:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 450, 129, 38));

        cbBloodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloodTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 458, 456, -1));

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 416, 456, 18));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 286, 456, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 370, 456, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Prenancy Information");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 506, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gravida:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 543, 68, 38));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LMP:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 587, 47, 38));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Midwives:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 637, 80, 38));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Para:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 543, 50, 38));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("EED");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 587, 42, 38));

        txtLMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLMPActionPerformed(evt);
            }
        });
        jPanel1.add(txtLMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 595, 202, -1));

        txtPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 551, 184, -1));

        txtGravida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGravidaActionPerformed(evt);
            }
        });
        jPanel1.add(txtGravida, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 551, 202, -1));

        txtEDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEDDActionPerformed(evt);
            }
        });
        jPanel1.add(txtEDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 595, 186, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ADD NEW PATIENT");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 476, 78));

        btnAddPatient.setText("Add");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 690, 90, 46));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 690, 90, 46));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 690, 90, 46));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, 29));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 323, -1, 29));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 590, 316, 29));

        cmbMidwives.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMidwives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMidwivesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbMidwives, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 645, 202, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pr_system1/25.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 1440, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            new PatientUI().setVisible(true); // open PatientUI
    this.dispose(); // close current AddPatientUI
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to clear all fields?", 
        "Confirm Clear", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAge.setText("");
        txtBirthDate.setText("");
        txtAddress.setText("");
        txtContactNo.setText("");
        cbBloodType.setSelectedIndex(0); // reset to first item
        txtGravida.setText("");
        txtPara.setText("");
        txtLMP.setText("");
        txtEDD.setText("");
    }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
            // 🧩 Step 1: Check required fields
    if (txtFirstName.getText().trim().isEmpty() ||
        txtLastName.getText().trim().isEmpty() ||
        txtAge.getText().trim().isEmpty() ||
        txtBirthDate.getText().trim().isEmpty() ||
        txtAddress.getText().trim().isEmpty() ||
        txtContactNo.getText().trim().isEmpty() ||
        cbBloodType.getSelectedIndex() == -1 ||
        txtGravida.getText().trim().isEmpty() ||
        txtPara.getText().trim().isEmpty() ||
        txtLMP.getText().trim().isEmpty() ||
        txtEDD.getText().trim().isEmpty() ||
        cmbMidwives.getSelectedIndex() <= 0) {

        JOptionPane.showMessageDialog(this,
            "⚠️ Please fill out all required fields before adding a new patient.",
            "Missing Information",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 🧩 Step 2: Validate date formats BEFORE inserting
    if (!txtBirthDate.getText().matches("\\d{2}/\\d{2}/\\d{4}") ||
        !txtLMP.getText().matches("\\d{2}/\\d{2}/\\d{4}") ||
        !txtEDD.getText().matches("\\d{2}/\\d{2}/\\d{4}")) {
        JOptionPane.showMessageDialog(this,
            "⚠️ Please use the correct date format: MM/DD/YYYY",
            "Invalid Date Format",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 🧩 Step 3: Get selected midwife ID
    String selectedMidwife = (String) cmbMidwives.getSelectedItem();
    String[] parts = selectedMidwife.split(" - ");
    int midwifeId = Integer.parseInt(parts[0]);

    // 🧩 Step 4: Insert into database
    try (Connection conn = DBConnection.getConnection()) {
        // 1️⃣ Insert patient
        String sqlPatient = """
            INSERT INTO patient_information 
            (first_name, last_name, age, birth_date, address, contact_no, blood_type, midwife_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """;
        PreparedStatement pst1 = conn.prepareStatement(sqlPatient, PreparedStatement.RETURN_GENERATED_KEYS);

        pst1.setString(1, txtFirstName.getText());
        pst1.setString(2, txtLastName.getText());
        pst1.setInt(3, Integer.parseInt(txtAge.getText()));
        pst1.setDate(4, java.sql.Date.valueOf(
            java.time.LocalDate.parse(txtBirthDate.getText(), java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"))));
        pst1.setString(5, txtAddress.getText());
        pst1.setString(6, txtContactNo.getText());
        pst1.setString(7, cbBloodType.getSelectedItem().toString());
        pst1.setInt(8, midwifeId);
        pst1.executeUpdate();

        ResultSet rs = pst1.getGeneratedKeys();
        int patientId = -1;
        if (rs.next()) patientId = rs.getInt(1);

        // 2️⃣ Insert pregnancy info
        String sqlPreg = """
            INSERT INTO pregnancy_information 
            (patient_id, gravida, para, lmp, eed)
            VALUES (?, ?, ?, ?, ?)
        """;
        PreparedStatement pst2 = conn.prepareStatement(sqlPreg);
        pst2.setInt(1, patientId);
        pst2.setInt(2, Integer.parseInt(txtGravida.getText()));
        pst2.setInt(3, Integer.parseInt(txtPara.getText()));
        pst2.setDate(4, java.sql.Date.valueOf(
            java.time.LocalDate.parse(txtLMP.getText(), java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"))));
        pst2.setDate(5, java.sql.Date.valueOf(
            java.time.LocalDate.parse(txtEDD.getText(), java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"))));
        pst2.executeUpdate();

        JOptionPane.showMessageDialog(this, "✅ New patient added successfully!");
        clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error adding patient: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void txtEDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEDDActionPerformed

    private void txtGravidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGravidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGravidaActionPerformed

    private void txtParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParaActionPerformed

    private void txtLMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLMPActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void cbBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloodTypeActionPerformed

    private void txtBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void cmbMidwivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMidwivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMidwivesActionPerformed

private void clearFields() {
    txtFirstName.setText("");
    txtLastName.setText("");
    txtAge.setText("");
    txtBirthDate.setText("");
    txtAddress.setText("");
    txtContactNo.setText("");
    cbBloodType.setSelectedIndex(0);
    txtGravida.setText("");
    txtPara.setText("");
    txtLMP.setText("");
    txtEDD.setText("");
    cmbMidwives.setSelectedIndex(0);
}


//  Place this OUTSIDE clearFields(), at the same level
private void addDateInputRestriction(javax.swing.JTextField textField) {
    textField.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '/' && c != '\b') {
                evt.consume(); // ignore invalid input
            }
        }
    });
}

private void addNumberOnlyRestriction(javax.swing.JTextField textField) {
    textField.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '\b') {
                evt.consume(); // ignore letters and symbols
            }
        }
    });
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddPatientUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cbBloodType;
    private javax.swing.JComboBox<String> cmbMidwives;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEDD;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGravida;
    private javax.swing.JTextField txtLMP;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPara;
    // End of variables declaration//GEN-END:variables
}
