/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pr_system1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author User PC
 */
public class EditPatientUI extends javax.swing.JFrame {
    private int patientId;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditPatientUI.class.getName());

    /**
     * Creates new form EditPatientUI
     */
    public EditPatientUI(int patientId) {
        initComponents();
        this.patientId = patientId;
        loadMidwives();
        
            // Add valid blood types
    cbBloodType.removeAllItems();
    cbBloodType.addItem("A+");
    cbBloodType.addItem("A-");
    cbBloodType.addItem("B+");
    cbBloodType.addItem("B-");
    cbBloodType.addItem("AB+");
    cbBloodType.addItem("AB-");
    cbBloodType.addItem("O+");
    cbBloodType.addItem("O-");
    
        loadPatientData(); // Load data when form opens
        addNumericRestriction(txtAge);
        addNumericRestriction(txtContactNo);
        addNumericRestriction(txtGravida);
        addNumericRestriction(txtPara);
        
        addDateInputRestriction(txtBirthDate);
        addDateInputRestriction(txtLMP);
        addDateInputRestriction(txtEED);
        
        
        
        
    }  
    
    // 🧩 Put this RIGHT BELOW the constructor (not inside it)
    private void loadPatientData() {
        try (Connection conn = DBConnection.getConnection()) {
            String sql = "SELECT * FROM patient_information WHERE patient_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, patientId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtFirstName.setText(rs.getString("first_name"));
                txtLastName.setText(rs.getString("last_name"));
                txtAge.setText(String.valueOf(rs.getInt("age")));
                txtBirthDate.setText(rs.getString("birth_date"));
                txtAddress.setText(rs.getString("address"));
                txtContactNo.setText(rs.getString("contact_no"));
                cbBloodType.setSelectedItem(rs.getString("blood_type"));
            }

            String sql2 = "SELECT * FROM pregnancy_information WHERE patient_id = ?";
            PreparedStatement pst2 = conn.prepareStatement(sql2);
            pst2.setInt(1, patientId);
            ResultSet rs2 = pst2.executeQuery();

            if (rs2.next()) {
                txtGravida.setText(String.valueOf(rs2.getInt("gravida")));
                txtPara.setText(String.valueOf(rs2.getInt("para")));
                txtLMP.setText(rs2.getString("lmp"));
                txtEED.setText(rs2.getString("eed"));;;;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading patient data: " + e.getMessage());
        }
    }
    
    // 🔹 Load all midwives into the combo box
private void loadMidwives() {
    try (Connection conn = DBConnection.getConnection()) {
        String sql = "SELECT midwife_id, full_name FROM midwife_information";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        cbMidwives.removeAllItems(); // clear combo box

        while (rs.next()) {
            // Example display: "1 - Maria Santos"
            cbMidwives.addItem(rs.getInt("midwife_id") + " - " + rs.getString("full_name"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading midwives: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtBirthDate = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        cbBloodType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtGravida = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLMP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPara = new javax.swing.JTextField();
        txtEED = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        cbMidwives = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EDIT PATIENT");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 64, 476, 78));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prenancy Information");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 512, 180, 38));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Birth Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 330, 129, 38));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 418, 129, 38));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("First Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 198, 108, 38));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Last Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 242, 129, 38));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Age:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 286, 129, 38));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 374, 129, 38));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Blood Type:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 462, 117, 38));

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 206, 346, -1));

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 250, 346, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 294, 346, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 382, 346, -1));

        txtBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBirthDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 338, 346, -1));

        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 426, 346, -1));

        cbBloodType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBloodType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBloodTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 470, 346, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 154, 129, 38));

        txtGravida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGravidaActionPerformed(evt);
            }
        });
        jPanel1.add(txtGravida, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 570, 290, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LMP:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 612, 111, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gravida:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 573, 111, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Midwives:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 652, 111, -1));

        txtLMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLMPActionPerformed(evt);
            }
        });
        jPanel1.add(txtLMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 609, 290, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Para:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 573, 78, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EED:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 612, 78, -1));

        txtPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPara, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 570, 232, -1));

        txtEED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEEDActionPerformed(evt);
            }
        });
        jPanel1.add(txtEED, new org.netbeans.lib.awtextra.AbsoluteConstraints(712, 609, 232, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 341, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 612, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("(MM/DD/YYYY)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 612, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 690, 90, 46));

        cbMidwives.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbMidwives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMidwivesActionPerformed(evt);
            }
        });
        jPanel1.add(cbMidwives, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 290, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 690, 90, 46));

        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 90, 46));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pr_system1/17.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -40, 1400, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBirthDateActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void cbBloodTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBloodTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBloodTypeActionPerformed

    private void txtGravidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGravidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGravidaActionPerformed

    private void txtLMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLMPActionPerformed

    private void txtParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParaActionPerformed

    private void txtEEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEEDActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    // 🧹 Clear all text fields
    txtFirstName.setText("");
    txtLastName.setText("");
    txtAge.setText("");
    txtBirthDate.setText("");
    txtAddress.setText("");
    txtContactNo.setText("");
    txtGravida.setText("");
    txtPara.setText("");
    txtLMP.setText("");
    txtEED.setText("");

    // 🩸 Reset combo boxes
    cbBloodType.setSelectedIndex(-1); // unselect blood type
    cbMidwives.setSelectedIndex(-1);  // unselect midwife

    // 🟢 Optional: Show message
    JOptionPane.showMessageDialog(this, "All fields have been cleared.");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
            new PatientUI().setVisible(true); // open PatientUI
            this.dispose(); // close current AddPatientUI
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbMidwivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMidwivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMidwivesActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        try (Connection conn = DBConnection.getConnection()) {

    // --- Date parsing helper ---
    java.sql.Date sqlBirthDate = parseDate(txtBirthDate.getText());
    java.sql.Date sqlLMP = parseDate(txtLMP.getText());
    java.sql.Date sqlEED = parseDate(txtEED.getText());

    // --- Update patient information ---
    String sql = "UPDATE patient_information SET first_name=?, last_name=?, age=?, birth_date=?, address=?, contact_no=?, blood_type=?, midwife_id=? WHERE patient_id=?";
    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, txtFirstName.getText());
    pst.setString(2, txtLastName.getText());
    pst.setInt(3, Integer.parseInt(txtAge.getText()));
    pst.setDate(4, sqlBirthDate);
    pst.setString(5, txtAddress.getText());
    pst.setString(6, txtContactNo.getText());
    pst.setString(7, cbBloodType.getSelectedItem().toString());
    pst.setString(7, cbBloodType.getSelectedItem().toString());

// Extract midwife_id from combo box text (before the "-")
String selected = cbMidwives.getSelectedItem().toString();
int midwifeId = Integer.parseInt(selected.split(" - ")[0]);
pst.setInt(8, midwifeId);

pst.setInt(9, patientId);
    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "✅ Patient updated successfully!");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "❌ Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnSave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void addDateInputRestriction(javax.swing.JTextField textField) {
    textField.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            String currentText = textField.getText();

            if (!Character.isDigit(c) && c != '/' && c != '\b') {
                evt.consume();
                return;
            }

            if (Character.isDigit(c)) {
                if (currentText.length() == 2 || currentText.length() == 5) {
                    textField.setText(currentText + "/");
                }
            }

            if (currentText.length() >= 10 && c != '\b') {
                evt.consume();
            }
        }
    });
}
// ✅ Allow only numbers (no letters, symbols)
private void addNumericRestriction(javax.swing.JTextField textField) {
    textField.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '\b') {
                evt.consume(); // block non-digit characters
            }
        }
    });
}

private java.sql.Date parseDate(String dateText) {
    if (dateText == null || dateText.trim().isEmpty()) {
        return null;
    }

    try {
        // Try MM/dd/yyyy first
        java.time.LocalDate localDate = java.time.LocalDate.parse(dateText, java.time.format.DateTimeFormatter.ofPattern("MM/dd/yyyy"));
        return java.sql.Date.valueOf(localDate);
    } catch (Exception e) {
        try {
            // Try yyyy-MM-dd (database format)
            java.time.LocalDate localDate = java.time.LocalDate.parse(dateText, java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd"));
            return java.sql.Date.valueOf(localDate);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "⚠ Invalid date format: " + dateText);
            return null;
        }
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    java.awt.EventQueue.invokeLater(() -> {
        // Run empty form just for testing (optional)
        new EditPatientUI(1).setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave1;
    private javax.swing.JComboBox<String> cbBloodType;
    private javax.swing.JComboBox<String> cbMidwives;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEED;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGravida;
    private javax.swing.JTextField txtLMP;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPara;
    // End of variables declaration//GEN-END:variables
}
