/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pr_system1;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.util.logging.Logger;
/**
 *
 * @author User PC
 */
public class MainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenu.class.getName());

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlogout = new javax.swing.JButton();
        jmidwives = new javax.swing.JButton();
        jcheckup = new javax.swing.JButton();
        jmedicalhistory = new javax.swing.JButton();
        jpatients = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prenatal Record System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jlogout.setText("Logout");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 389, 171, 40));

        jmidwives.setText("Midwives");
        jmidwives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmidwivesActionPerformed(evt);
            }
        });
        jPanel1.add(jmidwives, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 331, 171, 40));

        jcheckup.setText("Check-ups");
        jcheckup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckupActionPerformed(evt);
            }
        });
        jPanel1.add(jcheckup, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 215, 171, 40));

        jmedicalhistory.setText("History");
        jmedicalhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmedicalhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(jmedicalhistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 273, 171, 40));

        jpatients.setText("Patient Records");
        jpatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpatientsActionPerformed(evt);
            }
        });
        jPanel1.add(jpatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 157, 171, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pr_system1/6.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 530));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MainMenu");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 77, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpatientsActionPerformed
        // TODO add your handling code here:
    PatientUI patientWindow = new PatientUI();
    patientWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jpatientsActionPerformed

    private void jcheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckupActionPerformed
        // TODO add your handling code here:
    CheckupUI checkWindow = new CheckupUI();
    checkWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jcheckupActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
    login LoginWindow = new login();
    LoginWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jmedicalhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmedicalhistoryActionPerformed
        // TODO add your handling code here:
    MedicalHistoryUI historyWindow = new MedicalHistoryUI();
    historyWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmedicalhistoryActionPerformed

    private void jmidwivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmidwivesActionPerformed
        // TODO add your handling code here:
    MidwifeUI midWindow = new MidwifeUI();
    midWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jmidwivesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jcheckup;
    private javax.swing.JButton jlogout;
    private javax.swing.JButton jmedicalhistory;
    private javax.swing.JButton jmidwives;
    private javax.swing.JButton jpatients;
    // End of variables declaration//GEN-END:variables
}
